name: flutter_video_cast_example
description: Demonstrates how to use the flutter_video_cast plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
<<<<<<< HEAD
  sdk: '>=2.12.0-259.9.beta <3.0.0'
=======
  sdk: '>=2.12.0 <3.0.0'
>>>>>>> efc510aa2f891522ece4ffc7e22d9c59bda7aeb7

dependencies:
  flutter:
    sdk: flutter

  flutter_video_cast:
    path: ../

<<<<<<< HEAD
  cupertino_icons: ^1.0.2

=======
>>>>>>> efc510aa2f891522ece4ffc7e22d9c59bda7aeb7
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
